package com.autoparts.autoparts_system;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class AutopartsSystemApplication {

	private static final Logger log = LogManager.getLogger(AutopartsSystemApplication.class);

	AutopartsSystemApplication() {
		log.debug("AutopartsSystemApplication: starting application...");
	}

	public static void main(String[] args) {

		SpringApplication.run(AutopartsSystemApplication.class, args);
	}

}
